#!/bin/bash
# Quick Start Guide - Test Forgot Password OTP Fix

echo "======================================================================"
echo "         FORGOT PASSWORD OTP - QUICK START TESTING GUIDE"
echo "======================================================================"
echo ""

echo "✅ FIXES APPLIED:"
echo "   1. Removed development mode email skip"
echo "   2. Added comprehensive debugging"
echo "   3. Created interactive debug tool"
echo "   4. Created troubleshooting guide"
echo ""

echo "======================================================================"
echo "STEP 1: RUN THE INTERACTIVE DEBUGGER"
echo "======================================================================"
echo ""
echo "This is the EASIEST way to test and identify issues."
echo ""
echo "Run this command:"
echo "  cd server"
echo "  node debug-forgot-password-flow.js"
echo ""
echo "This will show you:"
echo "  ✓ Menu with 7 testing options"
echo "  ✓ Check environment configuration"
echo "  ✓ Test Gmail connection"
echo "  ✓ Test database connection"
echo "  ✓ Run full end-to-end test"
echo "  ✓ View OTP records"
echo "  ✓ Troubleshooting guide"
echo ""

echo "======================================================================"
echo "STEP 2: VERIFY GMAIL CREDENTIALS (CRITICAL)"
echo "======================================================================"
echo ""
echo "⚠️  Your Gmail password MUST be an App Password, not your regular password"
echo ""
echo "Check your .env file:"
echo "  cat server/.env | grep GMAIL"
echo ""
echo "Expected format:"
echo "  GMAIL_USER=noreplyrtx001@gmail.com"
echo "  GMAIL_PASSWORD=eibk klnu avsz abim   (16 chars WITH SPACES)"
echo ""
echo "If GMAIL_PASSWORD doesn't have spaces, follow this:"
echo "  1. Go to: https://myaccount.google.com/apppasswords"
echo "  2. Select App: Mail"
echo "  3. Select Device: Windows Computer"
echo "  4. Copy the generated password (with spaces)"
echo "  5. Update .env file:"
echo ""
echo "    GMAIL_PASSWORD=xxxx xxxx xxxx xxxx"
echo ""

echo "======================================================================"
echo "STEP 3: TEST THE API ENDPOINT"
echo "======================================================================"
echo ""
echo "Terminal 1 - Start the server:"
echo "  cd server"
echo "  node server.js"
echo ""
echo "Terminal 2 - Make a request:"
echo "  curl -X POST http://localhost:3005/api/auth/forgot-password \\\"
echo "    -H \"Content-Type: application/json\" \\\"
echo "    -d '{\"email\":\"testuser@example.com\"}'"
echo ""
echo "Terminal 1 - Check logs:"
echo "  Look for these sections:"
echo "  🔍 [OTP SEND] Starting OTP generation"
echo "  ✓ Step 1 - OTP Generated"
echo "  ✓ Step 3 - OTP Stored in Database"
echo "  🚀 [EMAIL SENDING]"
echo "  ✅ SUCCESS - Email sent successfully!"
echo ""

echo "======================================================================"
echo "STEP 4: VERIFY OTP IN DATABASE"
echo "======================================================================"
echo ""
echo "Check if OTP was stored:"
echo "  mysql -u root -p findsync -e \"SELECT * FROM password_reset_otp;\""
echo ""
echo "View OTP for specific email:"
echo "  mysql -u root -p findsync -e \""
echo "    SELECT email, otp, expires_at FROM password_reset_otp"
echo "    WHERE email='testuser@example.com';"
echo "  \""
echo ""

echo "======================================================================"
echo "STEP 5: TROUBLESHOOTING"
echo "======================================================================"
echo ""
echo "If OTP is not being sent:"
echo ""
echo "  1. Check that Gmail credentials are correct in .env"
echo "  2. Verify app password format (must have spaces)"
echo "  3. Run the debug tool (Option 1 & 2)"
echo "  4. Read: FORGOT_PASSWORD_DEBUG_GUIDE.md"
echo ""
echo "Common Issues:"
echo "  ❌ \"Authentication failed\""
echo "     → App Password format incorrect (missing spaces)"
echo ""
echo "  ❌ \"OTP not in database\""
echo "     → Database connection issue"
echo ""
echo "  ❌ \"Email not received\""
echo "     → Check server logs for step-by-step process"
echo ""

echo "======================================================================"
echo "QUICK REFERENCE COMMANDS"
echo "======================================================================"
echo ""
echo "Start debug tool:"
echo "  cd server && node debug-forgot-password-flow.js"
echo ""
echo "Start server:"
echo "  cd server && node server.js"
echo ""
echo "Test Gmail config:"
echo "  cd server && node test-gmail-config.js"
echo ""
echo "Test full OTP flow:"
echo "  cd server && node test-otp-flow.js"
echo ""
echo "Check environment:"
echo "  cat server/.env"
echo ""
echo "View OTP records:"
echo "  mysql -u root -p findsync -e 'SELECT * FROM password_reset_otp;'"
echo ""
echo "Delete old OTP records:"
echo "  mysql -u root -p findsync -e 'DELETE FROM password_reset_otp WHERE expires_at < NOW();'"
echo ""

echo "======================================================================"
echo "IMPORTANT: COMPREHENSIVE GUIDES CREATED"
echo "======================================================================"
echo ""
echo "📖 Read these files for more details:"
echo "   1. FORGOT_PASSWORD_FIX_SUMMARY.md"
echo "   2. FORGOT_PASSWORD_DEBUG_GUIDE.md"
echo ""
echo "======================================================================"
echo ""
echo "🚀 Ready to test? Start here:"
echo ""
echo "   cd server"
echo "   node debug-forgot-password-flow.js"
echo ""
echo "======================================================================"
